Details popup window
Benawi/Portifolio-Microverese pull request #18
Opened 2023-04-11 14:05 UTC by Benawi

## Portfolio - [Details popup window](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md)
### Features Added:
- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- When the user clicks (or taps) the close (X) button, the popup disappears.
- A JavaScript array used to store all of the information of all projects card.
- For each project  the following pieces of data  : name, description, featured image, technologies, link to live version, link to source stored in a JavaScript object.
- The recent work section is created when the page loads because the components are created dynamically using the information stored in that JavaScript.
- Popups(Modal) Implemented for both mobile and desktop screen sizes.
- I try to stick pages to the design as much as possible using [the templates 3 in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-468&t=Mj7DiWato4YlFqoE-0)
- No Linters errors
![image](https://user-images.githubusercontent.com/21217148/231277514-f60433cd-f43e-4575-ac85-178403042f8a.png)

2023-04-11 20:29 UTC, NahnahAJ commented
## Project Status: INVALIDATED :red_circle: 
Hi @Benawi , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

- [ ] This is because you have submitted a project, that is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode) and as a result, needs to have commits from both you and your partner or partners just as the first reviewer mentioned. :wink:
- [ ] If for some reason you had to work on the project alone, then please add a screenshot of the email you received from student success stating that you can work alone so the next reviewer can proceed to review your project :wink:
![image](https://user-images.githubusercontent.com/102699958/231280959-87287483-af98-49b4-a1e1-57ba74096886.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-12 09:30 UTC, levy002 requested changes
## Hello @Benawi   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter errors :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to align the project title at the beginning of the project card in order to match the provided Figma design.

   - ### YOUR DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/231411185-d474e426-c159-4e16-a266-714200f56e17.png)

   - ### FIGMA DESIGN
   
    ![image](https://user-images.githubusercontent.com/87197412/231411358-da5869fe-7695-4e5d-a3d4-74f4d28c65b3.png)


- [ ] KIndly make sure the background of the close icon on the desktop version looks the same s the provided Figma design.

  - ### YOUR DESIGN
  
    ![image](https://user-images.githubusercontent.com/87197412/231414031-38291e22-37ba-462f-9e69-fedebf3def63.png)

  - ### FIGMA DESIGN
  
    ![image](https://user-images.githubusercontent.com/87197412/231414127-599820be-79dd-462e-b96e-dcacb6767b51.png)


- [ ] Kindly make sure all contents of the project card are aligned at the beginning of the project card.

    - ### YOUR DESIGN
    ![chrome-capture-2023-3-12](https://user-images.githubusercontent.com/87197412/231415679-bc28d1f2-8aba-46b6-b8f1-0f9d1971ae6a.png)
    - ### FIGMA DESIGN
   ![image](https://user-images.githubusercontent.com/87197412/231415824-d1dabb00-9692-4f80-81cd-13239842c1ba.png)

- [ ] Kindly make sure the card is aligned in the center of the page in order to match the provided Figma design.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 09:30 UTC, levy002 commented on JS/Detail_Popup.js
> +  },
- [ ] Kindly make sure each project object at least contains the following information:
      - Name of the project :heavy_check_mark: 
      - Description of the project  :x: 
      - Project featured image :heavy_check_mark: 
      - Technologies used to build the project :heavy_check_mark: 
      - Link to the live version of the project :x: 
      - Link to the project source code :x: 


_**The reason why each project must have its own unique information it's because once you have the projects to fill in your Portfolio each project will have unique information different from the others. It is always better to plan ahead so it will be easy to update the Portfolio by just changing the placeholder project with real information**_

2023-04-12 13:06 UTC, Benawi commented
### CHANGES ♻️
-  Project title alignment changed in order to match the provided Figma design.
-  The background of the close icon on the desktop version changed which looks the same as the provided Figma design.
-  The contents of the project card aligned at the beginning
-  The card is aligned in the center of the page 
-  The object changed to contains the following information:
    - Name of the project ✔️
    -  Description of the project ✔️
    - Project featured image ✔️
    - Technologies used to build the project ✔️
    - Link to the live version of the project ✔️
    - Link to the project source code ✔️

2023-04-12 13:24 UTC, rotimiazeez approved these changes
Hi @Benawi 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job working on the required changes ✔️
- No linter error ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 13:36 UTC, merged