Portfolio: add a contact form and finish the mobile version
Benawi/Portifolio-Microverese pull request #7
Opened 2023-03-29 13:26 UTC by Benawi

## Implementation of recent works and About-me Sections
# Features Added:
- Contact form Added  to the portfolio 
- The footer  section adde to the portfolio 
- data  will be Collect  using an API [Formspree service](https://formspree.io/html).
- The button interactions Implement  (hover)
-  The following form validation added to the contact form
      - Name field accepts up to 30 chars.
      - Email field accepts only emails.
      - Message field accepts up to 500 chars.
      - All fields have placeholder text.
      - All fields have the correct type.
      - A user cannot submit the form if one or more of the fields is empty.
  - I try to stick the implimantaion to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

2023-03-29 14:20 UTC, gemmen29 requested changes
Hi @Benawi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 14:20 UTC, gemmen29 commented on index.html
> +      </h2>
- [ ] Kindly remove this text as it's existed twice to match the Figma design.
![image](https://user-images.githubusercontent.com/24703171/228565276-a5f43ba5-1663-43e1-b5fa-e41b2dbbbd96.png)

2023-03-29 14:20 UTC, gemmen29 commented on index.html
> +    </footer>
- To match the Figma design:
   - [ ] Kindly add the small background on the right. 
   - [ ] Kindly add your email between the `Get in touch` button and social media icons.
   - [ ] Please center the social media icons on the middle.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/24703171/228567087-b185e04d-1037-44b9-b765-6bceb0c442f7.png) | ![image](https://user-images.githubusercontent.com/24703171/228566636-56fe4624-981a-42c9-8a14-5c895568ae08.png) |

2023-03-30 06:32 UTC, Benawi commented
## CHANGES  ♻️
-  Email address added between the Get in touch button and social media icons.
- The social media icons set to the center
- small background added - responiseve
- The repeated text disabled for mobile version
![image](https://user-images.githubusercontent.com/21217148/228749203-bc18d4fc-fdb8-485f-99bb-11d9addcf7b5.png)

2023-03-30 06:39 UTC, gemmen29 approved these changes
Hi @Benawi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 11:05 UTC, merged